### ISSUE TITLE
Błąd "KeyError: 'NULL'" w czasie wyznaczania OUZ

### ISSUE THREAD

**Issue by sapas1** [CyfryzacjaAPP/wtyczka_qgis_app_2#22]
Chciałbym zgłosić występowanie błędu KeyError: 'NULL' w czasie wyznaczania OUZ.
Testowano na dwóch różnych komputerach, z QGIS w wersji 3.34.13 i 3.32.3, wtyczka w wersji 2.0.5.
(W10, prof PL 22H2, wszystkie patche wgrane, RAM 8G, na drugim 16G, nie obserwowałem problemów z zasobami w czasie prób) 
Błąd występuje zawsze przy 90% wykonania.

![obraz](https://github.com/user-attachments/assets/26e0b96c-cf0f-4953-b651-17394a0a0cfb)

### Opis błędu z 1 komputera:
Wystąpił błąd podczas wykonywania kodu Pythona: 
KeyError: 'NULL' 
Traceback (most recent call last):
  File "C:\Users/M/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wtyczka_qgis_app\modules\tworzenieOUZ\wtyczka_app.py", line 296, in tworzenieOUZ_btn_clicked
    AppModule.saveLayerToGML_OUZ(self, gkpg)
  File "C:\Users/M/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wtyczka_qgis_app\modules\app\wtyczka_app.py", line 1826, in saveLayerToGML_OUZ
    self.saveLayerToGML()
  File "C:\Users/M/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wtyczka_qgis_app\modules\app\wtyczka_app.py", line 1719, in saveLayerToGML
    atrybutHref.attrib['{http://www.w3.org/1999/xlink}href'] = attrs2Dic[attr.name()][str(obj.attribute(attr.name()))]
KeyError: 'NULL'

### Opis błędu z 2go komputera:
Wystąpił błąd podczas wykonywania kodu Pythona: 
KeyError: 'NULL' 
Traceback (most recent call last):
  File "C:\Users/dom/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wtyczka_qgis_app\modules\tworzenieOUZ\wtyczka_app.py", line 296, in tworzenieOUZ_btn_clicked
    AppModule.saveLayerToGML_OUZ(self, gkpg)
  File "C:\Users/dom/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wtyczka_qgis_app\modules\app\wtyczka_app.py", line 1826, in saveLayerToGML_OUZ
    self.saveLayerToGML()
  File "C:\Users/dom/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wtyczka_qgis_app\modules\app\wtyczka_app.py", line 1719, in saveLayerToGML
    atrybutHref.attrib['{[http://www.w3.org/1999/xlink}href'](http://www.w3.org/1999/xlink%7dhref')] = attrs2Dic[attr.name()][str(obj.attribute(attr.name()))]
KeyError: 'NULL'

Zrzuty ekranów:
![obraz](https://github.com/user-attachments/assets/24ed83c3-daa7-4c3c-b849-aa56fdab56ba)
![obraz](https://github.com/user-attachments/assets/43833101-4166-426f-9ea3-18ef1b14ce25)

Na dysku powstają jakieś tymczasowe warstwy, ale nie wiadomo czy kompletne/bezbłędne.

Dodatkowo widać poniższe ostrzeżenia:
![obraz](https://github.com/user-attachments/assets/ca250505-bfad-4109-9d6a-cc97fa8a61c7)
![obraz](https://github.com/user-attachments/assets/3e4f399a-058c-4e2c-a87b-fdce9c9cce77)
![obraz](https://github.com/user-attachments/assets/6996bca8-6534-4ae8-bebd-34b1c6c03108)

Wersja QGIS i wtyczki:
![obraz](https://github.com/user-attachments/assets/d34c67b2-0cb7-4f67-803f-89742e7c56ab)
![obraz](https://github.com/user-attachments/assets/95d7d2d9-29ac-4063-91ff-7494022704c2)
Na drugim kompie QGIS 3.32.3-Lima, wtyczka też 2.0.5.

Proszę o informację, co powoduje tego typu błąd lub proszę poprawkę.

04.12.2024 19:30

**Comment by CyfryzacjaAPP** [comment]
Dziękujemy za zgłoszenie. Prosimy o informację, jeśli opisana sytuacja powtarza się w najnowszej wersji Wtyczki APP 2.0.7. Wraz z informacją prosimy o przesłanie plików oraz używanej wersji Wtyczki APP oraz programu QGIS.
